### ISSUE TITLE
ALL returns should be sorted by pubyear

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_react#14]
This would require a backend change to the API.

**Comment by aazaff** [comment]
To clarify... most recent first.

**Comment by aazaff** [comment]
Is this implemented?

**Comment by NoisyFlowers** [comment]
This is in 
azgs/azlibrary_api@faf60e995bfc24147cbc5f2813acc474f2f96ac0

Currently on weave branch and running on dev

**Comment by aazaff** [comment]
I noticed that my very first load of dev was slow but then everything has been responsive and quick since then.
