### ISSUE TITLE
Update the alert box with latest update info

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_react#22]
Update the alert box code in layout.js 

New items to report
<li>Previous search results are now saved on back-button.</li>
<li>Can now directly open individual PDFs instead of downloading entire zip. Please note we have reports of this feature not working properly on Mozilla Firefox.</li>

Was there anything else we changed from an end-user perspective?

**Comment by NoisyFlowers** [comment]
- Maps no longer grab cursor unexpectedly. Must click once on map to interact.

**Comment by NoisyFlowers** [comment]
This is in 74a884fbc26b5d46d1bc1d24f3c39dffa50cd309

deployed to al2 instance
