### ISSUE TITLE
New home for geomapaz

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_react#23]
https://geomapaz.azgs.arizona.edu/

We currently run the following app from People's Host, the same way we used to run https://library.azgs.arizona.edu/.

The code for it is here https://github.com/azgs/Geologic-Map-of-Arizona-Leaflet.

I am curious if there is a way for us to have this served from the current AZLib serverv instead as we are trying to close out our People's Host account? I'm assuming just through a diff nginx port?

**Comment by NoisyFlowers** [comment]
Yeah, I think you're right. 

I can try this on dev next week, if it's a priority.

**Comment by NoisyFlowers** [comment]
Can we get UITS to route dev.geomapaz.azgs.arizona.edu to our dev server for experimentation?

**Comment by NoisyFlowers** [comment]
Works great, except we forgot about the cert. Need to have them do whatever to get that working too.

**Comment by aazaff** [comment]
Cert procedure is now working correctly on Dev. Having them repeat the procedure for prod. When can I switch over?

**Comment by aazaff** [comment]
Turns out this is moot because in a completely unrelated turn of events they want to shut down the geomap...
