### ISSUE TITLE
Figure out how to implement Google tag

### ISSUE THREAD

**Issue by NoisyFlowers** [azgs/azlibrary_react#24]
Andrew uses GTM to monitor the react client. Not sure how this worked before our shambling change to AL2, but need to figure out how to make it work there.

**Comment by NoisyFlowers** [comment]
This is implemented using react-gtm-module in d13473d088ef5ae82b9c96c520f7e982e2a6b2a9

merged to main and running on prod

Note: This requires that a REACT_APP_GTMID be set in .env

**Comment by aazaff** [comment]
This is not actually working in the sense that google analytics is still not receiving any information as of now. I will check in again tomorrow to make sure it is not just a delay in propagation.
![Screenshot 2024-03-26 at 12 02 01 PM](https://github.com/azgs/azlibrary_react/assets/10422595/bcc9a739-f80b-4397-813b-b37dbe49e595)

**Comment by aazaff** [comment]
Confirmed it is still not working. I added @NoisyFlowers to the stache for the analytics.google.com account so he can do testing on his own if necessary. 

AZGS Google Analytics is the name of the stache entry.

**Comment by aazaff** [comment]
Can we bump this back up in priority now that we have some breathing room? @NoisyFlowers

**Comment by NoisyFlowers** [comment]
Changing the ID appears to have fixed this. Can we close?
