### ISSUE TITLE
Change search to be on submit?

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_react#26]
As @NoisyFlowers and many others have pointed out. The current setup of having the results happen in real-time is just too unfamiliar to user. People want an on-button event to open a new search page. 

Not sure when to prioritize this change or if we even should make this change or we should just make people get used to it. Either way, finally documenting the issue.

**Comment by NoisyFlowers** [comment]
This is in 
22966be119c6bcf755f1c001239302a674a78257
958da51c74e0d51667510fbd6f8d0f961aeca880

On ddm-dev branch, running on dev

**Comment by aazaff** [comment]
Change the help/notification blurb 

From: 
 > The operation of the form now requires an explicit action to get fresh results. This is a more common paradigm than the previous live form and cuts down on roundtrips to the API.

> In response to user-feedback, you must now hit the *Apply Filters* button to execute a search.
