### ISSUE TITLE
Client does not parse multiple lineages correctly.

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_react#27]
I'm putting this as an enhancement/bug because
1. The way it is currently implemented isn't working since collection names are just smooshed together making an unworkable link.

2. Even if it was working, it would look pretty ugly. Can we think of a better design/layout for presenting this information?

![Screenshot 2024-04-23 at 9 45 42 AM](https://github.com/azgs/azlibrary_react/assets/10422595/28a62b61-5556-420d-ac60-950e9ba73b40)

> The three superseding collections are smooshed together. Not only does it look bad it doesn't work cause it will try to take you to a bogus collection.

![Screenshot 2024-04-23 at 9 46 00 AM](https://github.com/azgs/azlibrary_react/assets/10422595/f64884bb-6599-4ba6-893d-31123c8be70e)

**Comment by NoisyFlowers** [comment]
This is fixed in 3e3b2a1601cf6f5a9893f1373caa89d966331764

on ddm-dev branch, running on dev
