### ISSUE TITLE
File Download Links Not Working for DGM-77

### ISSUE THREAD

**Issue by livingstonsn** [azgs/azlibrary_react#30]
I am attempting to access the GIS data for DGM-77 (Geologic Map of the Wintersburg 7.5' Quadrangle) and none of the file download links work.  Is there an alternate location to access the data?

**Comment by aazaff** [comment]
Hello, all data on our repository is mirrored at the UA Campus repository - https://repository.arizona.edu
The specific map you are looking for is here https://repository.arizona.edu/handle/10150/629377.
